repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        exclude: data/
        args:
          - --fix
          - --target-version=py311
          - --ignore=E721,E722
          - --line-length=80
      - id: nbqa-black
        exclude: data/
        args:
          - --line-length=80
      - id: nbqa-isort
        exclude: data/
        args:
          - --profile=black
          - --float-to-top

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: name-tests-test
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: pretty-format-json
        exclude_types: [jupyter]
        args:
          - --autofix

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: Run isort to sort imports
        types_or: [python, pyi]
        exclude: ^build/.*$|^.tox/.*$|^venv/.*$|data/
        args:
          - --lines-after-imports=2
          - --profile=black
          - --line-length=80

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        types_or: [python,pyi]
        exclude: data/
        args:
          - --fix
          - --target-version=py311
          - --select=B,C,E,F,W
          - --ignore=E203,E402,E501,W391,E261
          - --line-length=80
      - id: ruff-format
        exclude: data/
        types_or: [python,pyi]
        args:
          - --target-version=py311
          - --line-length=80
