[tool.poetry]
name = "one-offs"
version = "0.1.0"
description = ""
authors = ["michplunkett <michplunkett@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "one_offs"}]

[tool.black]
line-length = 80

[tool.poetry.dependencies]
python = "^3.11"
black = "^23.1.0"
pylint = "^2.17.0"
google-cloud-translate = "2.0.1"
pillow = "^9.5.0"
pytesseract = "^0.3.10"
pdf2image = "^1.16.3"
isort = "^5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
