name: Lint
on:
  - push
  - pull_request
jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - name: Black
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          src: ./test/ ./google_translate_pdfs/ ./geocode_verifier/ ./util/
          options: --check --verbose
          version: ^23.1.0
  ISort:
    runs-on: ubuntu-latest
    steps:
      - name: isort
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - uses: isort/isort-action@master
        with:
          configuration: --check-only --diff
          requirementsFiles: pyproject.toml
          sortPaths: ./test/ ./google_translate_pdfs/ ./geocode_verifier/ ./util/
