name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          options: --check --verbose
          version: ~= 23.1.0
  ISort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: isort/isort-action@master
        with:
          configuration: --check-only --diff
          requirementsFiles: pyproject.toml
